# Generated by Django 4.1.3 on 2022-11-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_moviecomment_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewcomment',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='moviecomment',
            name='parent_comment',
        ),
    ]
