# Generated by Django 4.1.3 on 2022-11-26 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_crewcomment_parent_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewcomment',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviecomment',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
